version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10

  server:
    image: shareit_server_image:latest
    container_name: shareit-server
    depends_on:
     - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "9090:9090"
      - "9091:9091"

  gateway:
    image: shareit_gateway_image:latest
    container_name: shareit-gateway
    depends_on:
      server:
        condition: service_started
    environment:
      PORT: 8080
      SHAREIT_SERVER_URL: http://server:9090
    ports:
      - "8080:8080"

volumes:
  pgdata: