DELETE FROM bookings ;
DELETE FROM items ;
DELETE FROM users ;

ALTER SEQUENCE bookings_id_seq RESTART WITH 1;
ALTER SEQUENCE items_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;

