CREATE SEQUENCE IF NOT EXISTS USERS_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT DEFAULT NEXTVAL('USERS_ID_SEQ') PRIMARY KEY,
    name  TEXT NOT NULL,
    email TEXT UNIQUE
);


CREATE SEQUENCE IF NOT EXISTS REQUESTS_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT DEFAULT NEXTVAL('REQUESTS_ID_SEQ') PRIMARY KEY,
    requestor_id BIGINT REFERENCES users (id) NOT NULL,
    description  TEXT NOT NULL
);


CREATE SEQUENCE IF NOT EXISTS ITEMS_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT DEFAULT NEXTVAL('ITEMS_ID_SEQ') PRIMARY KEY,
    name         TEXT    NOT NULL,
    description  TEXT    NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id     BIGINT  NOT NULL,
    request_id   BIGINT
);

CREATE SEQUENCE IF NOT EXISTS BOOKINGS_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT DEFAULT NEXTVAL('BOOKINGS_ID_SEQ') PRIMARY KEY,
    item_id    BIGINT REFERENCES items (id) NOT NULL,
    booker_id  BIGINT REFERENCES users (id) NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    status     TEXT
);

CREATE SEQUENCE IF NOT EXISTS COMMENTS_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT DEFAULT NEXTVAL('COMMENTS_ID_SEQ') PRIMARY KEY,
    item_id      BIGINT REFERENCES items (id) NOT NULL,
    author_id    BIGINT REFERENCES users (id) NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
    text         TEXT
);