DELETE FROM requests ;
DELETE FROM comments ;
DELETE FROM bookings ;
DELETE FROM items ;
DELETE FROM users ;

ALTER SEQUENCE requests_id_seq RESTART WITH 1;
ALTER SEQUENCE comments_id_seq RESTART WITH 1;
ALTER SEQUENCE bookings_id_seq RESTART WITH 1;
ALTER SEQUENCE items_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;